[package]
name = "nino-api"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_builder = "0.12.0"
quick-xml = "0.31.0"
reqwest = "0.11.23"
rocket = { version = "0.5.0", features = ["secrets", "json"] }
serde = "1.0.193"
