[package]
name = "nino-api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
derive_builder = "0.12.0"
quick-xml = "0.31.0"
reqwest = "0.11.23"
rocket = { version = "0.5.0" }
thiserror = "1.0.53"
